### PR TITLE
Fix celo dynamic tx receipt encoding

### PR DESCRIPTION
**Pull request by piersy**
The old code assumed that CeloDynamicFeeTxV2Type receipts had a base fee defined, that is not the case for migrated receipts that have no base fee. So the base fee was made optional to allow decoding migrated CeloDynamicFeeTxV2Type receipts. Also we don't try to derive fields using nil base fees from migrated CeloDynamicFeeTxV2Type receipts.

Also CeloDynamicFeeTxType receipts were not being handled in receipt decodeing paths, so would throw an unknown type error.

### CODE REVIEW

**Comment by palango** [comment]
Looks good, but I'm not really experienced in this part of the code. Could you add some test for de/encoding of receipts to make sure this all works?

**Review by alecps — APPROVED** [review]

**Comment by alecps** [comment]
@piersy We'd need to test this via the RPC api right?

**Comment by piersy** [comment]
@palango Added a test for encoding/decoding of our typed receipts. Also added an [issue](https://github.com/celo-org/celo-blockchain-planning/issues/359) to add a test for ensuring the correct effectiveGasPriceDerivation, I don't think it's as pressing as the encode/decode for now.

**Review by palango — APPROVED** [review]

**Comment by piersy** [comment]
@alecps we can test it via the RPC and that would be the most comprehensive test, but we can at least test that encoding followed by decoding doesn't result in any errors and results in the same object.

**Pull request merged**
