### PR TITLE
Move base fee conversion out of `TransactionToMessage`

### PR DESCRIPTION
**Pull request by palango**
@karlb as discussed yesterday, this moves the base fee conversion out of `TransactionToMessage`

### CODE REVIEW

**Review by karlb — COMMENTED** [review]
That's more places where `TransactionToMessage` is called (and thus a larger diff) than I thought. In the optimism repo there are actually only two calls to this function, so looking at the overall change, it would be easier to change it there. But it feels nice to have the diff to upstream contained in one repository with this PR.
Maybe having a different signature is even a good thing, as we can't accidentally pass a non-converted baseFees anymore. What do you think?

**Comment by palango** [comment]
> But it feels nice to have the diff to upstream contained in one repository with this PR.

Wouldn't you require changes in the optimism repo anyways? Or not because all transactions there are non-Celo ones?

> Maybe having a different signature is even a good thing, as we can't accidentally pass a non-converted baseFees anymore. What do you think?

I'm torn, it feels a bit cleaner to leave the signature as it is, but I agree that that might introduce subtle bugs.

All of this wouldn't be necessary with the celo denominated transaction. ;)

**Comment by karlb** [comment]
> Wouldn't you require changes in the optimism repo anyways? Or not because all transactions there are non-Celo ones?

In one place yes, in the other it doesn't because the baseFee is `nil` anyway.

> I'm torn, it feels a bit cleaner to leave the signature as it is, but I agree that that might introduce subtle bugs.

Considering that I would have surely missed one necessary change in the optimism repo during this rebase, my tend towards not merging this PR. I'm sorry for creating the extra work!

> All of this wouldn't be necessary with the celo denominated transaction. ;)

Yes, no diff in optimism repo for that and still no way to cause a bug. Would be really nice in this case.

**Comment by palango** [comment]
Ok, sounds good to me, we can always reevaluate later.

**Pull request closed without merging**
